version: '3'
services:
  app:
    container_name: wego
    restart: always
    build: .
    ports:
      - '3001:3001'
    external_links:
      - localhost
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
